"""
pdf_extractor.py — PyMuPDF (fitz) Document Extractor with Font Normalization.

Extracts text spans, bounding boxes, typographic attributes, and layout blocks
from Word-generated PDF documents into the canonical Document Intermediate Representation (IR).
Enforces mandatory font subset prefix stripping (e.g. BAAAAA+Calibri -> Calibri).
"""
from __future__ import annotations

import io
import re
from pathlib import Path
from typing import BinaryIO, Union

try:
    import fitz  # PyMuPDF
    HAS_FITZ = True
except ImportError:
    HAS_FITZ = False

from .ir import Color, Document, Page, Paragraph, Run


def strip_font_subset_prefix(font_name: str) -> str:
    """
    Mandatory Invariant Normalization:
    Strips 6-uppercase-letter random subset prefixes generated by Word during PDF export.
    Example: 'BAAAAA+Calibri' -> 'Calibri', 'XYZABC+TimesNewRoman-Bold' -> 'TimesNewRoman-Bold'.
    """
    if not font_name:
        return "Calibri"
    clean = re.sub(r"^[A-Z]{6}\+", "", font_name).strip()
    return clean if clean else "Calibri"


def clean_base_font_family(font_name: str) -> str:
    """Extracts the base font family name without style suffixes."""
    stripped = strip_font_subset_prefix(font_name)
    # Remove style suffixes like -Bold, -Italic, ,Bold, etc.
    base = re.split(r"[-_,]", stripped)[0].strip()
    return base if base else "Calibri"


class PDFExtractor:
    """Extracts structured Document IR from PDF documents using PyMuPDF."""

    def __init__(self, space_gap_threshold_ratio: float = 0.25) -> None:
        if not HAS_FITZ:
            raise ImportError(
                "PyMuPDF (fitz) is required for PDFExtractor. "
                "Install via: pip install pymupdf"
            )
        self.space_gap_threshold_ratio = space_gap_threshold_ratio

    def extract(self, source: Union[str, Path, bytes, BinaryIO]) -> Document:
        """Extracts Document IR from file path, raw bytes, or stream."""
        if isinstance(source, (str, Path)):
            doc_fitz = fitz.open(str(source))
        elif isinstance(source, bytes):
            doc_fitz = fitz.open(stream=source, filetype="pdf")
        else:
            doc_fitz = fitz.open(stream=source.read(), filetype="pdf")

        try:
            return self._process_fitz_doc(doc_fitz)
        finally:
            doc_fitz.close()

    def _process_fitz_doc(self, doc_fitz: fitz.Document) -> Document:
        doc = Document()

        for page_idx in range(len(doc_fitz)):
            page_fitz = doc_fitz[page_idx]
            rect = page_fitz.rect
            page = doc.add_page(width_pts=rect.width, height_pts=rect.height)
            page_data = page_fitz.get_text("dict")

            for block in page_data.get("blocks", []):
                # type 0 = text block, 1 = image block
                if block.get("type") != 0:
                    continue

                para = self._process_text_block(block)
                if para.runs:
                    page.blocks.append(para)

        return doc

    def _process_text_block(self, block: dict) -> Paragraph:
        """Translates a PyMuPDF text block into a canonical Paragraph IR."""
        para = Paragraph()
        lines = block.get("lines", [])
        if not lines:
            return para

        for l_idx, line in enumerate(lines):
            spans = line.get("spans", [])
            for s_idx, span in enumerate(spans):
                text = span.get("text", "")
                if not text:
                    continue

                raw_font = span.get("font", "Calibri")
                clean_font = clean_base_font_family(raw_font)
                font_size = float(span.get("size", 11.0))
                flags = span.get("flags", 0)

                # Flag 2 = italic, Flag 16 = bold
                is_bold = bool(flags & 16) or "bold" in raw_font.lower()
                is_italic = bool(flags & 2) or "italic" in raw_font.lower() or "oblique" in raw_font.lower()

                # Color parsing from integer sRGB
                c_int = span.get("color", 0)
                r = (c_int >> 16) & 255
                g = (c_int >> 8) & 255
                b = c_int & 255
                color = Color(r=r, g=g, b=b)

                # Check if we need to insert a space before this span due to horizontal gap
                if s_idx > 0 and para.runs:
                    prev_bbox = spans[s_idx - 1].get("bbox", (0, 0, 0, 0))
                    curr_bbox = span.get("bbox", (0, 0, 0, 0))
                    dx = curr_bbox[0] - prev_bbox[2]
                    threshold = font_size * self.space_gap_threshold_ratio
                    if dx > threshold and not para.runs[-1].text.endswith(" ") and not text.startswith(" "):
                        text = " " + text

                para.add_run(
                    text=text,
                    font=clean_font,
                    font_size_pt=font_size,
                    bold=is_bold,
                    italic=is_italic,
                    color=color,
                )

            # Between lines in the same block, ensure word separation
            if l_idx < len(lines) - 1 and para.runs and not para.runs[-1].text.endswith(" "):
                para.runs[-1].text += " "

        return para


def extract_pdf(source: Union[str, Path, bytes, BinaryIO]) -> Document:
    """Convenience helper to extract Document IR from a PDF."""
    return PDFExtractor().extract(source)
