"""
pdf_extractor.py — PyMuPDF (fitz) Document Extractor with Font Normalization.

Extracts text spans, bounding boxes, typographic attributes, and layout blocks
from Word-generated PDF documents into the canonical Document Intermediate Representation (IR).
Enforces mandatory font subset prefix stripping (e.g. BAAAAA+Calibri -> Calibri).
"""
from __future__ import annotations

import io
import re
from pathlib import Path
from typing import BinaryIO, Union

try:
    import fitz  # PyMuPDF
    HAS_FITZ = True
except ImportError:
    HAS_FITZ = False

from .ir import Block, Cell, Color, Document, Page, Paragraph, Row, Run, Table
from .genome import ProfilePolicy


def strip_font_subset_prefix(font_name: str) -> str:
    """
    Mandatory Invariant Normalization:
    Strips 6-uppercase-letter random subset prefixes generated by Word during PDF export.
    Example: 'BAAAAA+Calibri' -> 'Calibri', 'XYZABC+TimesNewRoman-Bold' -> 'TimesNewRoman-Bold'.
    """
    if not font_name:
        return "Calibri"
    clean = re.sub(r"^[A-Z]{6}\+", "", font_name).strip()
    return clean if clean else "Calibri"


def clean_base_font_family(font_name: str) -> str:
    """Extracts the base font family name without style suffixes."""
    stripped = strip_font_subset_prefix(font_name)
    # Remove style suffixes like -Bold, -Italic, ,Bold, etc.
    base = re.split(r"[-_,]", stripped)[0].strip()
    # Normalize common Word PostScript font family suffixes (PS, MT, PSMT)
    base = re.sub(r"(PSMT|PS|MT)$", "", base, flags=re.IGNORECASE).strip()
    # Map common standard fonts to canonical display names
    low = base.lower()
    if low in ("timesnewroman", "times"):
        return "Times New Roman"
    if low == "arial":
        return "Arial"
    if low == "calibri":
        return "Calibri"
    if low == "georgia":
        return "Georgia"
    if low in ("helvetica", "helv"):
        return "Helvetica"
    return base if base else "Calibri"


class PDFExtractor:
    """Extracts structured Document IR from PDF documents using PyMuPDF and tunable heuristic policies."""

    def __init__(
        self,
        space_gap_threshold_ratio: float = 0.25,
        policy: ProfilePolicy | None = None,
    ) -> None:
        if not HAS_FITZ:
            raise ImportError(
                "PyMuPDF (fitz) is required for PDFExtractor. "
                "Install via: pip install pymupdf"
            )
        if policy is not None:
            self.policy = policy
            self.space_gap_threshold_ratio = policy.space_gap_ratio
        else:
            self.space_gap_threshold_ratio = space_gap_threshold_ratio
            self.policy = ProfilePolicy(space_gap_ratio=space_gap_threshold_ratio)

    def extract(self, source: Union[str, Path, bytes, BinaryIO]) -> Document:
        """Extracts Document IR from file path, raw bytes, or stream."""
        if isinstance(source, (str, Path)):
            doc_fitz = fitz.open(str(source))
        elif isinstance(source, bytes):
            doc_fitz = fitz.open(stream=source, filetype="pdf")
        else:
            doc_fitz = fitz.open(stream=source.read(), filetype="pdf")

        try:
            return self._process_fitz_doc(doc_fitz)
        finally:
            doc_fitz.close()

    def _process_fitz_doc(self, doc_fitz: fitz.Document) -> Document:
        doc = Document()

        for page_idx in range(len(doc_fitz)):
            page_fitz = doc_fitz[page_idx]
            rect = page_fitz.rect
            page = doc.add_page(width_pts=rect.width, height_pts=rect.height)

            # Detect tables on this page
            tables_fitz = []
            table_bboxes = []
            if hasattr(page_fitz, "find_tables"):
                try:
                    tabs = page_fitz.find_tables()
                    for t in getattr(tabs, "tables", []):
                        if (
                            t.row_count >= self.policy.table_min_rows
                            and t.col_count >= self.policy.table_min_cols
                        ):
                            tables_fitz.append(t)
                            table_bboxes.append(t.bbox)
                except Exception:
                    pass

            elements_to_place: list[tuple[float, float, Block]] = []

            # Process tables into Table IR
            for t in tables_fitz:
                t_ir = Table(alignment="left")
                extracted_data = t.extract()
                for r_idx, row_cells in enumerate(extracted_data):
                    is_hdr = (r_idx == 0)
                    r_ir = Row(is_header=is_hdr)
                    for cell_val in row_cells:
                        val_str = str(cell_val or "").strip()
                        c_ir = Cell(width_twips=2880)
                        if val_str:
                            c_ir.add_paragraph(
                                val_str, font="Calibri", font_size_pt=10.0, bold=is_hdr
                            )
                        r_ir.cells.append(c_ir)
                    t_ir.rows.append(r_ir)
                elements_to_place.append((t.bbox[1], t.bbox[3], t_ir))

            page_data = page_fitz.get_text("dict")

            # Estimate page margins from text blocks
            text_blocks_bboxes = [
                b["bbox"] for b in page_data.get("blocks", []) if b.get("type") == 0
            ]
            min_x0 = min((b[0] for b in text_blocks_bboxes), default=72.0)
            margin_left = min_x0 if min_x0 >= 10.0 else 72.0
            margin_right = margin_left

            for block in page_data.get("blocks", []):
                # type 0 = text block, 1 = image block
                if block.get("type") != 0:
                    continue

                bbox = block.get("bbox", (0, 0, 0, 0))
                # Skip text block if its center falls inside a recognized table
                bx_center = (bbox[0] + bbox[2]) / 2.0
                by_center = (bbox[1] + bbox[3]) / 2.0
                in_table = any(
                    (tb[0] <= bx_center <= tb[2] and tb[1] <= by_center <= tb[3])
                    for tb in table_bboxes
                )
                if in_table:
                    continue

                para_entries = self._process_text_block(
                    block,
                    page_width=rect.width,
                    margin_left=margin_left,
                    margin_right=margin_right,
                )
                for p_y0, p_y1, p in para_entries:
                    if p.runs and p.plain_text.strip():
                        elements_to_place.append((p_y0, p_y1, p))

            # Sort all elements (paragraphs and tables) vertically by y0
            elements_to_place.sort(key=lambda item: item[0])

            # Calculate inter-element vertical spacing (space_before_pt and space_after_pt)
            grid = max(0.1, self.policy.line_spacing_round_pt)
            for el_idx in range(1, len(elements_to_place)):
                prev_y1 = elements_to_place[el_idx - 1][1]
                curr_y0 = elements_to_place[el_idx][0]
                gap = curr_y0 - prev_y1
                prev_el = elements_to_place[el_idx - 1][2]
                curr_el = elements_to_place[el_idx][2]
                if gap > 2.0:
                    rounded_gap = round(gap / grid) * grid
                    clamped_gap = min(rounded_gap, 144.0)
                    if isinstance(curr_el, Paragraph):
                        curr_el.space_before_pt = clamped_gap
                    elif isinstance(prev_el, Paragraph):
                        prev_el.space_after_pt = clamped_gap

            for _, _, el in elements_to_place:
                page.blocks.append(el)

        return doc

    def _process_text_block(
        self,
        block: dict,
        page_width: float = 612.0,
        margin_left: float = 72.0,
        margin_right: float = 72.0,
    ) -> list[tuple[float, float, Paragraph]]:
        """Translates a PyMuPDF text block into canonical Paragraphs with layout bounds and line spacing."""
        raw_lines = block.get("lines", [])
        if not raw_lines:
            return []

        # Group lines into paragraphs based on vertical line spacing delta
        line_groups: list[list[dict]] = []
        current_group: list[dict] = []

        for l_idx, line in enumerate(raw_lines):
            if not current_group:
                current_group.append(line)
                continue

            prev_line = current_group[-1]
            prev_bbox = prev_line.get("bbox", (0, 0, 0, 0))
            curr_bbox = line.get("bbox", (0, 0, 0, 0))
            line_height = max(1.0, prev_bbox[3] - prev_bbox[1])
            dy = curr_bbox[1] - prev_bbox[3]

            # If vertical gap exceeds the policy threshold, split into new paragraph
            if dy > (line_height * self.policy.para_split_delta_ratio):
                line_groups.append(current_group)
                current_group = [line]
            else:
                current_group.append(line)

        if current_group:
            line_groups.append(current_group)

        paragraphs: list[tuple[float, float, Paragraph]] = []
        grid = max(0.1, self.policy.line_spacing_round_pt)

        for group in line_groups:
            para = Paragraph()
            # Calculate horizontal and vertical bounds
            x0_min = min((l.get("bbox", (0, 0, 0, 0))[0] for l in group), default=0.0)
            x1_max = max((l.get("bbox", (0, 0, 0, 0))[2] for l in group), default=page_width)
            y0_min = min((l.get("bbox", (0, 0, 0, 0))[1] for l in group), default=0.0)
            y1_max = max((l.get("bbox", (0, 0, 0, 0))[3] for l in group), default=0.0)

            content_right = page_width - margin_right
            content_center = page_width / 2.0
            block_center = (x0_min + x1_max) / 2.0
            line_span_width = x1_max - x0_min
            content_width = max(1.0, content_right - margin_left)

            # Heuristic alignment classification
            is_centered = abs(block_center - content_center) <= self.policy.align_tolerance_pt
            is_flush_left = abs(x0_min - margin_left) <= max(3.0, self.policy.align_tolerance_pt)
            is_justified = (
                len(group) > 1
                and is_flush_left
                and any(
                    abs(l.get("bbox", (0, 0, 0, 0))[2] - content_right) <= self.policy.align_tolerance_pt
                    for l in group[:-1]
                )
                and (content_right - group[-1].get("bbox", (0, 0, 0, 0))[2]) > (self.policy.align_tolerance_pt * 2)
            )

            if is_justified:
                para.alignment = "justify"
            elif is_centered and (not is_flush_left or line_span_width < (content_width * 0.95)):
                para.alignment = "center"
            elif (
                abs(x1_max - content_right) <= self.policy.align_tolerance_pt
                and (x0_min - margin_left) > (self.policy.align_tolerance_pt * 2)
            ):
                para.alignment = "right"
            else:
                para.alignment = "left"

            # Compute inter-line spacing for multi-line paragraphs using line_spacing_round_pt
            if len(group) > 1:
                line_y_diffs = [
                    group[i].get("bbox", (0, 0, 0, 0))[1] - group[i - 1].get("bbox", (0, 0, 0, 0))[1]
                    for i in range(1, len(group))
                ]
                if line_y_diffs:
                    avg_ls = sum(line_y_diffs) / len(line_y_diffs)
                    para.line_spacing_pt = round(avg_ls / grid) * grid
            else:
                para.line_spacing_pt = None

            # Process spans within group
            for l_idx, line in enumerate(group):
                spans = line.get("spans", [])
                for s_idx, span in enumerate(spans):
                    text = span.get("text", "")
                    if not text:
                        continue

                    raw_font = span.get("font", "Calibri")
                    clean_font = clean_base_font_family(raw_font)
                    font_size = float(span.get("size", 11.0))
                    flags = span.get("flags", 0)

                    is_bold = bool(flags & 16) or "bold" in raw_font.lower()
                    is_italic = bool(flags & 2) or "italic" in raw_font.lower() or "oblique" in raw_font.lower()

                    c_int = span.get("color", 0)
                    r = (c_int >> 16) & 255
                    g = (c_int >> 8) & 255
                    b = c_int & 255
                    color = Color(r=r, g=g, b=b)

                    if s_idx > 0 and para.runs:
                        prev_bbox = spans[s_idx - 1].get("bbox", (0, 0, 0, 0))
                        curr_bbox = span.get("bbox", (0, 0, 0, 0))
                        dx = curr_bbox[0] - prev_bbox[2]
                        threshold = font_size * self.space_gap_threshold_ratio
                        if dx > threshold and not para.runs[-1].text.endswith(" ") and not text.startswith(" "):
                            text = " " + text

                    para.add_run(
                        text=text,
                        font=clean_font,
                        font_size_pt=font_size,
                        bold=is_bold,
                        italic=is_italic,
                        color=color,
                    )

                if l_idx < len(group) - 1 and para.runs and not para.runs[-1].text.endswith(" "):
                    para.runs[-1].text += " "

            if para.runs:
                paragraphs.append((y0_min, y1_max, para))

        return paragraphs


def extract_pdf(source: Union[str, Path, bytes, BinaryIO]) -> Document:
    """Convenience helper to extract Document IR from a PDF."""
    return PDFExtractor().extract(source)
