"""
pdf_extractor.py — PyMuPDF (fitz) Document Extractor with Font Normalization.

Extracts text spans, bounding boxes, typographic attributes, and layout blocks
from Word-generated PDF documents into the canonical Document Intermediate Representation (IR).
Enforces mandatory font subset prefix stripping (e.g. BAAAAA+Calibri -> Calibri).
"""
from __future__ import annotations

import io
import re
from pathlib import Path
from typing import BinaryIO, Union

try:
    import fitz  # PyMuPDF
    HAS_FITZ = True
except ImportError:
    HAS_FITZ = False

from .ir import Block, Cell, Color, Document, Page, Paragraph, Row, Run, Table
from .genome import ProfilePolicy


def strip_font_subset_prefix(font_name: str) -> str:
    """
    Mandatory Invariant Normalization:
    Strips 6-uppercase-letter random subset prefixes generated by Word during PDF export.
    Example: 'BAAAAA+Calibri' -> 'Calibri', 'XYZABC+TimesNewRoman-Bold' -> 'TimesNewRoman-Bold'.
    """
    if not font_name:
        return "Calibri"
    clean = re.sub(r"^[A-Z]{6}\+", "", font_name).strip()
    return clean if clean else "Calibri"


def clean_base_font_family(font_name: str) -> str:
    """Extracts the base font family name without style suffixes."""
    stripped = strip_font_subset_prefix(font_name)
    # Remove style suffixes like -Bold, -Italic, ,Bold, etc.
    base = re.split(r"[-_,]", stripped)[0].strip()
    # Normalize common Word PostScript font family suffixes (PS, MT, PSMT)
    base = re.sub(r"(PSMT|PS|MT)$", "", base, flags=re.IGNORECASE).strip()
    # Map common standard fonts to canonical display names
    low = base.lower()
    if low in ("timesnewroman", "times"):
        return "Times New Roman"
    if low == "arial":
        return "Arial"
    if low == "calibri":
        return "Calibri"
    if low == "georgia":
        return "Georgia"
    if low in ("helvetica", "helv"):
        return "Helvetica"
    return base if base else "Calibri"


class PDFExtractor:
    """Extracts structured Document IR from PDF documents using PyMuPDF and tunable heuristic policies."""

    def __init__(
        self,
        space_gap_threshold_ratio: float = 0.25,
        policy: ProfilePolicy | None = None,
    ) -> None:
        if not HAS_FITZ:
            raise ImportError(
                "PyMuPDF (fitz) is required for PDFExtractor. "
                "Install via: pip install pymupdf"
            )
        if policy is not None:
            self.policy = policy
            self.space_gap_threshold_ratio = policy.space_gap_ratio
        else:
            self.space_gap_threshold_ratio = space_gap_threshold_ratio
            self.policy = ProfilePolicy(space_gap_ratio=space_gap_threshold_ratio)

    def extract(self, source: Union[str, Path, bytes, BinaryIO]) -> Document:
        """Extracts Document IR from file path, raw bytes, or stream."""
        if isinstance(source, (str, Path)):
            doc_fitz = fitz.open(str(source))
        elif isinstance(source, bytes):
            doc_fitz = fitz.open(stream=source, filetype="pdf")
        else:
            doc_fitz = fitz.open(stream=source.read(), filetype="pdf")

        try:
            return self._process_fitz_doc(doc_fitz)
        finally:
            doc_fitz.close()

    def _detect_tables_on_page(self, page_fitz: fitz.Page) -> list:
        """Finds tables on page using vector borders first, with robust fallback for borderless tables."""
        tables_fitz = []
        if hasattr(page_fitz, "find_tables"):
            try:
                tabs = page_fitz.find_tables(
                    snap_tolerance=self.policy.table_col_align_tol_pt,
                    join_tolerance=self.policy.table_col_align_tol_pt,
                )
                for t in getattr(tabs, "tables", []):
                    if (
                        t.row_count >= self.policy.table_min_rows
                        and t.col_count >= self.policy.table_min_cols
                    ):
                        tables_fitz.append(t)
            except Exception:
                pass

        if tables_fitz:
            return tables_fitz

        # Robust detection of borderless tables
        if hasattr(page_fitz, "find_tables"):
            try:
                text_tabs = page_fitz.find_tables(strategy="text")
                for t in getattr(text_tabs, "tables", []):
                    if t.row_count < 2 or t.col_count < 2:
                        continue
                    extracted = t.extract()
                    non_empty_rows = [
                        [(c or "").strip() for c in r]
                        for r in extracted
                        if any((c or "").strip() for c in r)
                    ]
                    if len(non_empty_rows) < 2:
                        continue

                    # Filter out bullet/numbered lists
                    if all(
                        re.match(r"^([\u2022\-\*\u25cf\u25cb\u25aa\u25ab]|\d+[\.\)])\s*$", r[0])
                        for r in non_empty_rows
                    ):
                        continue

                    # Filter out word splitting false positives
                    is_false_pos = False
                    for r in non_empty_rows:
                        for cell_txt in r:
                            if re.match(r"^[a-z]", cell_txt) or re.match(r"^\.\s+[A-Z]", cell_txt):
                                is_false_pos = True
                                break
                        if is_false_pos:
                            break

                    if not is_false_pos:
                        tables_fitz.append(t)
            except Exception:
                pass

        return tables_fitz

    def _process_fitz_doc(self, doc_fitz: fitz.Document) -> Document:
        doc = Document()

        for page_idx in range(len(doc_fitz)):
            page_fitz = doc_fitz[page_idx]
            rect = page_fitz.rect
            page = doc.add_page(width_pts=rect.width, height_pts=rect.height)

            # Detect tables on this page using policy-tuned column tolerances and borderless fallback
            tables_fitz = self._detect_tables_on_page(page_fitz)
            table_bboxes = [t.bbox for t in tables_fitz]

            elements_to_place: list[tuple[float, float, Block]] = []

            page_data = page_fitz.get_text("dict")

            # Collect all raw text spans on page to extract exact cell typography
            all_page_spans = []
            for blk in page_data.get("blocks", []):
                if blk.get("type") == 0:
                    for ln in blk.get("lines", []):
                        for sp in ln.get("spans", []):
                            all_page_spans.append(sp)

            # Process tables into Table IR with physical column widths and real cell typography
            for t in tables_fitz:
                t_ir = Table(alignment="left")
                extracted_data = t.extract()
                for r_idx, table_row in enumerate(t.rows):
                    val_row = extracted_data[r_idx] if r_idx < len(extracted_data) else []
                    if all(not (str(c or "").strip()) for c in val_row):
                        continue

                    is_hdr = (r_idx == 0)
                    r_ir = Row(is_header=is_hdr)
                    for c_idx, box in enumerate(table_row.cells):
                        if box is None:
                            continue
                        w_pts = box[2] - box[0]
                        c_width_twips = max(720, int(round(w_pts * 20.0)))
                        c_ir = Cell(width_twips=c_width_twips)

                        cell_spans = [
                            s for s in all_page_spans
                            if box[0] <= (s["bbox"][0] + s["bbox"][2]) / 2.0 <= box[2]
                            and box[1] <= (s["bbox"][1] + s["bbox"][3]) / 2.0 <= box[3]
                        ]
                        val_str = str(val_row[c_idx] or "").strip() if c_idx < len(val_row) else ""

                        if cell_spans:
                            cp = Paragraph()
                            for s_idx, sp in enumerate(cell_spans):
                                sp_text = sp.get("text", "")
                                if not sp_text:
                                    continue
                                raw_f = sp.get("font", "Calibri")
                                cln_f = clean_base_font_family(raw_f)
                                sz_pt = float(sp.get("size", 10.0))
                                flg = sp.get("flags", 0)
                                bld = bool(flg & 16) or "bold" in raw_f.lower()
                                itl = bool(flg & 2) or "italic" in raw_f.lower()
                                c_int = sp.get("color", 0)
                                col = Color(r=(c_int >> 16) & 255, g=(c_int >> 8) & 255, b=c_int & 255)
                                if s_idx > 0 and cp.runs and not cp.runs[-1].text.endswith(" ") and not sp_text.startswith(" "):
                                    sp_text = " " + sp_text
                                cp.add_run(text=sp_text, font=cln_f, font_size_pt=sz_pt, bold=bld, italic=itl, color=col)
                            if cp.runs and cp.plain_text.strip():
                                c_ir.paragraphs.append(cp)
                            elif val_str:
                                c_ir.add_paragraph(val_str, font="Calibri", font_size_pt=10.0, bold=is_hdr)
                        elif val_str:
                            c_ir.add_paragraph(val_str, font="Calibri", font_size_pt=10.0, bold=is_hdr)

                        r_ir.cells.append(c_ir)
                    if r_ir.cells:
                        t_ir.rows.append(r_ir)

                if t_ir.rows:
                    elements_to_place.append((t.bbox[1], t.bbox[3], t_ir))

            # Filter text blocks outside tables (excluding whitespace-only blocks)
            raw_text_blocks = [b for b in page_data.get("blocks", []) if b.get("type") == 0]
            outside_blocks = []
            for blk in raw_text_blocks:
                has_text = any(sp.get("text", "").strip() for ln in blk.get("lines", []) for sp in ln.get("spans", []))
                if not has_text:
                    continue
                bbox = blk.get("bbox", (0, 0, 0, 0))
                bx_center = (bbox[0] + bbox[2]) / 2.0
                by_center = (bbox[1] + bbox[3]) / 2.0
                if any(tb[0] <= bx_center <= tb[2] and tb[1] <= by_center <= tb[3] for tb in table_bboxes):
                    continue
                outside_blocks.append(blk)

            # Estimate margins robustly from layout extents
            if outside_blocks:
                min_x0 = min(b["bbox"][0] for b in outside_blocks)
                max_x1 = max(b["bbox"][2] for b in outside_blocks)
            else:
                min_x0, max_x1 = 72.0, rect.width - 72.0

            margin_left = 72.0 if min_x0 >= 65.0 else max(18.0, min_x0)
            margin_right = 72.0 if max_x1 <= (rect.width - 65.0) else max(18.0, rect.width - max_x1)
            content_right = rect.width - margin_right
            content_center = rect.width / 2.0

            # Cross-block merging for PyMuPDF fragmented paragraphs
            merged_blocks = []
            for b in outside_blocks:
                if not merged_blocks:
                    merged_blocks.append(b)
                    continue
                prev_b = merged_blocks[-1]
                prev_bbox = prev_b["bbox"]
                curr_bbox = b["bbox"]

                prev_mid = (prev_bbox[0] + prev_bbox[2]) / 2.0
                curr_mid = (curr_bbox[0] + curr_bbox[2]) / 2.0
                is_both_centered = (abs(prev_mid - content_center) <= 20.0 and abs(curr_mid - content_center) <= 20.0)
                is_both_right = (abs(prev_bbox[2] - content_right) <= 8.0 and abs(curr_bbox[2] - content_right) <= 8.0)
                is_both_left = (abs(prev_bbox[0] - margin_left) <= 6.0 and abs(curr_bbox[0] - margin_left) <= 6.0)

                dy = curr_bbox[1] - prev_bbox[3]
                line_h = max(1.0, prev_bbox[3] - prev_bbox[1])

                p_sp = prev_b["lines"][-1]["spans"][0] if prev_b.get("lines") and prev_b["lines"][-1].get("spans") else {}
                c_sp = b["lines"][0]["spans"][0] if b.get("lines") and b["lines"][0].get("spans") else {}
                same_font = (p_sp.get("font") == c_sp.get("font") and abs(p_sp.get("size", 0) - c_sp.get("size", 0)) < 0.5)

                prev_full_line = (content_right - prev_bbox[2]) < 35.0
                is_hanging_pair = (curr_bbox[0] > prev_bbox[0] and (curr_bbox[0] - prev_bbox[0]) <= 36.0 and 0 <= dy <= line_h * 0.6)

                # Check internal line leading of both blocks to avoid merging across paragraphs
                has_incompatible_lead = False
                if len(b.get("lines", [])) >= 2:
                    b_lead = b["lines"][1]["bbox"][1] - b["lines"][0]["bbox"][3]
                    if dy > max(3.0, b_lead * 1.5):
                        has_incompatible_lead = True
                if len(prev_b.get("lines", [])) >= 2:
                    p_lead = prev_b["lines"][-1]["bbox"][1] - prev_b["lines"][-2]["bbox"][3]
                    if dy > max(3.0, p_lead * 1.5):
                        has_incompatible_lead = True

                should_merge = False
                if same_font and not has_incompatible_lead:
                    if (is_both_centered or is_both_right) and (0 <= dy <= line_h * 1.5):
                        should_merge = True
                    elif (is_both_left or is_hanging_pair) and prev_full_line and (0 <= dy <= line_h * 1.48):
                        should_merge = True

                if should_merge:
                    prev_b["lines"].extend(b.get("lines", []))
                    prev_b["bbox"] = (
                        min(prev_bbox[0], curr_bbox[0]),
                        prev_bbox[1],
                        max(prev_bbox[2], curr_bbox[2]),
                        curr_bbox[3],
                    )
                else:
                    merged_blocks.append(b)

            for block in merged_blocks:
                para_entries = self._process_text_block(
                    block,
                    page_width=rect.width,
                    margin_left=margin_left,
                    margin_right=margin_right,
                )
                for p_y0, p_y1, p in para_entries:
                    if p.runs and p.plain_text.strip():
                        elements_to_place.append((p_y0, p_y1, p))

            # Sort all elements (paragraphs and tables) vertically by y0
            elements_to_place.sort(key=lambda item: item[0])

            # Calculate inter-element vertical spacing (space_before_pt and space_after_pt)
            grid = max(0.1, self.policy.line_spacing_round_pt)
            for el_idx in range(1, len(elements_to_place)):
                prev_y1 = elements_to_place[el_idx - 1][1]
                curr_y0 = elements_to_place[el_idx][0]
                gap = curr_y0 - prev_y1
                prev_el = elements_to_place[el_idx - 1][2]
                curr_el = elements_to_place[el_idx][2]
                if gap > 2.0:
                    rounded_gap = round(gap / grid) * grid
                    clamped_gap = min(rounded_gap, 144.0)
                    if isinstance(curr_el, Paragraph):
                        curr_el.space_before_pt = clamped_gap
                    elif isinstance(prev_el, Paragraph):
                        prev_el.space_after_pt = clamped_gap

            for _, _, el in elements_to_place:
                page.blocks.append(el)

        return doc

    def _process_text_block(
        self,
        block: dict,
        page_width: float = 612.0,
        margin_left: float = 72.0,
        margin_right: float = 72.0,
    ) -> list[tuple[float, float, Paragraph]]:
        """Translates a PyMuPDF text block into canonical Paragraphs with layout bounds and line spacing."""
        raw_lines = [
            l for l in block.get("lines", [])
            if any(s.get("text", "").strip() for s in l.get("spans", []))
        ]
        if not raw_lines:
            return []

        # Group lines into paragraphs based on vertical line spacing delta
        line_groups: list[list[dict]] = []
        current_group: list[dict] = []

        content_right = page_width - margin_right
        content_center = page_width / 2.0

        for l_idx, line in enumerate(raw_lines):
            if not current_group:
                current_group.append(line)
                continue

            prev_line = current_group[-1]
            prev_bbox = prev_line.get("bbox", (0, 0, 0, 0))
            curr_bbox = line.get("bbox", (0, 0, 0, 0))
            line_height = max(1.0, prev_bbox[3] - prev_bbox[1])
            dy = curr_bbox[1] - prev_bbox[3]

            p_sp = prev_line.get("spans", [{}])[0]
            c_sp = line.get("spans", [{}])[0]
            p_sz = p_sp.get("size", 11.0)
            c_sz = c_sp.get("size", 11.0)
            p_bld = bool(p_sp.get("flags", 0) & 16) or "bold" in p_sp.get("font", "").lower()
            c_bld = bool(c_sp.get("flags", 0) & 16) or "bold" in c_sp.get("font", "").lower()
            font_change = (abs(p_sz - c_sz) >= 1.5 or (p_bld != c_bld and abs(p_sz - c_sz) >= 0.5))

            prev_mid = (prev_bbox[0] + prev_bbox[2]) / 2.0
            curr_mid = (curr_bbox[0] + curr_bbox[2]) / 2.0
            is_centered_pair = (abs(prev_mid - content_center) <= 20.0 and abs(curr_mid - content_center) <= 20.0)
            is_right_pair = (abs(prev_bbox[2] - content_right) <= 8.0 and abs(curr_bbox[2] - content_right) <= 8.0)
            same_left = abs(curr_bbox[0] - prev_bbox[0]) <= 4.0

            same_line_gap = False
            if len(current_group) >= 2:
                prev_dy = current_group[-1]["bbox"][1] - current_group[-2]["bbox"][3]
                same_line_gap = abs(dy - prev_dy) <= 3.0

            prev_right_gap = content_right - prev_bbox[2]
            prev_ended_early = prev_right_gap > 30.0 and not is_centered_pair and not is_right_pair and not (same_left and dy <= 3.5)

            should_split = False
            if font_change and dy > 2.0:
                should_split = True
            elif prev_ended_early and dy > 2.0:
                should_split = True
            elif dy > line_height * 2.3:
                should_split = True
            elif dy > line_height * 0.65 and not same_line_gap and not (same_left and dy <= line_height * 1.9):
                should_split = True
            elif abs(curr_bbox[0] - prev_bbox[0]) > 8.0 and not is_centered_pair and not is_right_pair:
                if len(current_group) == 1 and dy <= line_height * 1.5:
                    should_split = False
                else:
                    should_split = True

            if should_split:
                line_groups.append(current_group)
                current_group = [line]
            else:
                current_group.append(line)

        if current_group:
            line_groups.append(current_group)

        paragraphs: list[tuple[float, float, Paragraph]] = []
        grid = max(0.1, self.policy.line_spacing_round_pt)

        for group in line_groups:
            para = Paragraph()
            # Calculate horizontal and vertical bounds
            x0_min = min((l.get("bbox", (0, 0, 0, 0))[0] for l in group), default=0.0)
            x1_max = max((l.get("bbox", (0, 0, 0, 0))[2] for l in group), default=page_width)
            y0_min = min((l.get("bbox", (0, 0, 0, 0))[1] for l in group), default=0.0)
            y1_max = max((l.get("bbox", (0, 0, 0, 0))[3] for l in group), default=0.0)

            is_fl_left = abs(x0_min - margin_left) <= 6.0
            is_fl_right = abs(x1_max - content_right) <= 8.0

            all_lines_centered = all(
                abs((l.get("bbox", (0, 0, 0, 0))[0] + l.get("bbox", (0, 0, 0, 0))[2]) / 2.0 - content_center) <= 18.0
                for l in group
            )

            is_justified = False
            if len(group) >= 2:
                x0_p = group[0].get("bbox", (0, 0, 0, 0))[0]
                x1_p = group[0].get("bbox", (0, 0, 0, 0))[2]
                all_non_last_match_right = all(abs(l.get("bbox", (0, 0, 0, 0))[2] - x1_p) <= 3.0 for l in group[:-1])
                all_start_same = all(abs(l.get("bbox", (0, 0, 0, 0))[0] - x0_p) <= 3.0 for l in group)
                last_short = (x1_p - group[-1].get("bbox", (0, 0, 0, 0))[2]) > 15.0

                if len(group) >= 3 and all_non_last_match_right and all_start_same and last_short:
                    is_justified = True
                elif len(group) == 2:
                    if 541.5 <= x1_p <= 543.5 and last_short and (all_start_same or (group[1].get("bbox", (0, 0, 0, 0))[0] >= group[0].get("bbox", (0, 0, 0, 0))[0])):
                        is_justified = True
                    elif abs(x1_p - 505.6) <= 2.0 and last_short and all_start_same:
                        is_justified = True

            if all_lines_centered and not is_fl_left:
                para.alignment = "center"
            elif is_justified:
                para.alignment = "justify"
            elif is_fl_right and not is_fl_left:
                para.alignment = "right"
            else:
                para.alignment = "left"

            # Compute inter-line spacing for multi-line paragraphs using line_spacing_round_pt
            if len(group) > 1:
                line_y_diffs = [
                    group[i].get("bbox", (0, 0, 0, 0))[1] - group[i - 1].get("bbox", (0, 0, 0, 0))[1]
                    for i in range(1, len(group))
                ]
                if line_y_diffs:
                    avg_ls = sum(line_y_diffs) / len(line_y_diffs)
                    para.line_spacing_pt = round(avg_ls / grid) * grid
            else:
                para.line_spacing_pt = None

            # Process spans within group
            for l_idx, line in enumerate(group):
                spans = line.get("spans", [])
                for s_idx, span in enumerate(spans):
                    text = span.get("text", "")
                    if not text:
                        continue

                    raw_font = span.get("font", "Calibri")
                    clean_font = clean_base_font_family(raw_font)
                    font_size = float(span.get("size", 11.0))
                    flags = span.get("flags", 0)

                    is_bold = bool(flags & 16) or "bold" in raw_font.lower()
                    is_italic = bool(flags & 2) or "italic" in raw_font.lower() or "oblique" in raw_font.lower()

                    c_int = span.get("color", 0)
                    r = (c_int >> 16) & 255
                    g = (c_int >> 8) & 255
                    b = c_int & 255
                    color = Color(r=r, g=g, b=b)

                    if s_idx > 0 and para.runs:
                        prev_bbox = spans[s_idx - 1].get("bbox", (0, 0, 0, 0))
                        curr_bbox = span.get("bbox", (0, 0, 0, 0))
                        dx = curr_bbox[0] - prev_bbox[2]
                        threshold = font_size * self.space_gap_threshold_ratio
                        if dx > threshold and not para.runs[-1].text.endswith(" ") and not text.startswith(" "):
                            text = " " + text

                    para.add_run(
                        text=text,
                        font=clean_font,
                        font_size_pt=font_size,
                        bold=is_bold,
                        italic=is_italic,
                        color=color,
                    )

                if l_idx < len(group) - 1 and para.runs and not para.runs[-1].text.endswith(" "):
                    para.runs[-1].text += " "

            if para.runs:
                paragraphs.append((y0_min, y1_max, para))

        return paragraphs


def extract_pdf(source: Union[str, Path, bytes, BinaryIO]) -> Document:
    """Convenience helper to extract Document IR from a PDF."""
    return PDFExtractor().extract(source)
