"""evolab — Universal Evolutionary Optimization & Synthesis Kernel across Software, Silicon, Discrete Logic, and Mathematics.

Importing this package loads the core evolutionary kernel and domain adapter contracts.
"""
from __future__ import annotations

from typing import Any

__version__ = "0.5.0"

from .adapters import (
    DomainAdapter,
    ElectronicsAdapter,
    DiscreteLogicAdapter,
    NumericalMathAdapter,
    SoftwareRepairAdapter,
    get_domain_adapter,
    list_domain_adapters,
    register_domain_adapter,
)
from .pareto import (
    NSGA2Engine,
    Objective,
    MultiObjectiveResult,
    fast_non_dominated_sort,
    calculate_crowding_distance,
    build_silicon_multiobjective_evaluator,
)
from .swe_bench import (
    SWEBenchAdapter,
    SWEBenchInstance,
    SWEBenchResolution,
)
from .analyzer import summarize
from .code_fixtures import (
    SCENARIO_REGISTRY,
    CodeScenario,
    get_all_scenarios,
    load_pytest_scenario,
    load_scenario_file,
    load_source_scenario,
    make_code_population,
    scenario_click_parser,
    scenario_lru_cache_logic,
    scenario_multi_file_config,
    scenario_requests_auth_url,
)
from .config import EngineConfig, MemoryConfig, QualityDiversityConfig, SpeciationConfig
from .engine import (
    SPECIES_POOL,
    EvolutionEngine,
    default_fitness,
    genomic_distance,
    ragged_fitness,
    species_cfg,
)
from .evaluators import (
    CompileCheckEvaluator,
    Evaluator,
    FitnessResult,
    FunctionTestEvaluator,
    NumericEvaluator,
    SandboxFunctionTestEvaluator,
)
from .genome import EvolabGenome, FloatGenome, Individual
from .repair import (
    RepairEdit,
    RepairGenome,
    apply_edits,
    catalog_edits,
    list_repair_patterns,
    register_repair_pattern,
    unregister_repair_pattern,
)
from .reporters import (
    apply_in_place,
    format_git_patch,
    format_markdown_summary,
    format_terminal_diagnostics,
)
from .schema import Issue, RunReport, parse_report, save_report

_LAZY: dict[str, tuple[str, str]] = {
    # patch / AST / CST
    "Hunk": (".patch", "Hunk"),
    "PatchGenome": (".patch", "PatchGenome"),
    "PatchApplyError": (".patch", "PatchApplyError"),
    "apply_patch": (".patch", "apply_patch"),
    "create_patch_from_diff": (".patch", "create_patch_from_diff"),
    "patch_distance": (".patch", "patch_distance"),
    "mutate_patch": (".patch", "mutate_patch"),
    "mutate_multi_hunk": (".patch", "mutate_multi_hunk"),
    "NodeAnchor": (".anchored_patch", "NodeAnchor"),
    "AnchoredHunk": (".anchored_patch", "AnchoredHunk"),
    "AnchoredPatchGenome": (".anchored_patch", "AnchoredPatchGenome"),
    "apply_anchored_hunk": (".anchored_patch", "apply_anchored_hunk"),
    "AnchoredPatchApplyError": (".anchored_patch", "AnchoredPatchApplyError"),
    "ASTSemanticGuard": (".ast_guard", "ASTSemanticGuard"),
    "is_ast_change_safe": (".ast_guard", "is_ast_change_safe"),
    "ASTGenome": (".ast_genome", "ASTGenome"),
    "MultiFileASTGenome": (".ast_genome", "MultiFileASTGenome"),
    "ast_distance": (".ast_genome", "ast_distance"),
    "mutate_ast": (".ast_genome", "mutate_ast"),
    "crossover_ast": (".ast_genome", "crossover_ast"),
    "get_ast_metrics": (".ast_genome", "get_ast_metrics"),
    "compute_cyclomatic_complexity": (".ast_genome", "compute_cyclomatic_complexity"),
    "create_random_ast_genome": (".ast_genome", "create_random_ast_genome"),
    "CSTGenome": (".cst_genome", "CSTGenome"),
    "CSTConstantMutator": (".cst_genome", "CSTConstantMutator"),
    "CSTComparisonMutator": (".cst_genome", "CSTComparisonMutator"),
    "CSTBinaryOpMutator": (".cst_genome", "CSTBinaryOpMutator"),
    "CSTSemanticNodeCollector": (".cst_genome", "CSTSemanticNodeCollector"),
    "NodeType": (".real_ast", "NodeType"),
    "NodeMetadata": (".real_ast", "NodeMetadata"),
    "CriticalityLevel": (".real_ast", "CriticalityLevel"),
    "Symbol": (".real_ast", "Symbol"),
    "TypeInfo": (".real_ast", "TypeInfo"),
    "SymbolTable": (".real_ast", "SymbolTable"),
    "DeepAnalyzer": (".real_ast", "DeepAnalyzer"),
    "DependencyAnalyzer": (".real_ast", "DependencyAnalyzer"),
    "IntelligentMutator": (".real_ast", "IntelligentMutator"),
    "BalancedMutator": (".real_ast", "BalancedMutator"),
    "IntelligentCrossover": (".real_ast", "IntelligentCrossover"),
    "ASTOptimizer": (".real_ast", "ASTOptimizer"),
    "RealASTGenome": (".real_ast", "RealASTGenome"),
    "SuspicionMap": (".suspicion", "SuspicionMap"),
    "SuspiciousNode": (".suspicion", "SuspiciousNode"),
    "LineCoverageTracer": (".suspicion", "LineCoverageTracer"),
    "build_suspicion_map": (".suspicion", "build_suspicion_map"),
    "FaultGuidedASTMutator": (".suspicion", "FaultGuidedASTMutator"),
    "compute_ochiai_score": (".suspicion", "compute_ochiai_score"),
    "SandboxConfig": (".sandbox", "SandboxConfig"),
    "SandboxRunner": (".sandbox", "SandboxRunner"),
    "ExecutionResult": (".sandbox", "ExecutionResult"),
    "EliteTypeCheckGate": (".type_gate", "EliteTypeCheckGate"),
    "TypeCheckResult": (".type_gate", "TypeCheckResult"),
    "CallSite": (".cross_file", "CallSite"),
    "ImportInfo": (".cross_file", "ImportInfo"),
    "CrossFileDependencyGraph": (".cross_file", "CrossFileDependencyGraph"),
    "CrossFileMutator": (".cross_file", "CrossFileMutator"),
    "EventBus": (".events", "EventBus"),
    "EvolutionEvent": (".events", "EvolutionEvent"),
    "GenerationEvaluatedEvent": (".events", "GenerationEvaluatedEvent"),
    "IndividualEvaluatedEvent": (".events", "IndividualEvaluatedEvent"),
    "MutationRejectedEvent": (".events", "MutationRejectedEvent"),
    "RunCompletedEvent": (".events", "RunCompletedEvent"),
    "FitnessLandscape": (".landscapes", "FitnessLandscape"),
    "SmoothProxyLandscape": (".landscapes", "SmoothProxyLandscape"),
    "RastriginLandscape": (".landscapes", "RastriginLandscape"),
    "TrapKLandscape": (".landscapes", "TrapKLandscape"),
    "NoisyWrapper": (".landscapes", "NoisyWrapper"),
    "MovingTargetLandscape": (".landscapes", "MovingTargetLandscape"),
    "build_landscape": (".landscapes", "build_landscape"),
    "CausalEvent": (".causal", "CausalEvent"),
    "CausalModel": (".causal", "CausalModel"),
    "TrapSignatureLibrary": (".causal", "TrapSignatureLibrary"),
    "StrategicMutationSelector": (".causal", "StrategicMutationSelector"),
    "discretize_context": (".causal", "discretize_context"),
    "discretize_code_context": (".causal", "discretize_code_context"),
    "ExperienceStore": (".experience", "ExperienceStore"),
    "ExperienceMutationPrior": (".experience", "ExperienceMutationPrior"),
    "ExperienceSequencePrior": (".experience", "ExperienceSequencePrior"),
    "ExperienceRecorderProxy": (".experience", "ExperienceRecorderProxy"),
    "attach_experience_recorder": (".experience", "attach_experience_recorder"),
    "EvaluationCache": (".experience", "EvaluationCache"),
    "attach_eval_cache": (".experience", "attach_eval_cache"),
    "problem_fingerprint": (".experience", "problem_fingerprint"),
    "function_summaries": (".experience", "function_summaries"),
    "render_family_report": (".experience", "render_family_report"),
    "ZProtocolConfig": (".z_protocol", "ZProtocolConfig"),
    "ZProtocolEngine": (".z_protocol", "ZProtocolEngine"),
    "LLMConfig": (".llm_mutator", "LLMConfig"),
    "LLMResponse": (".llm_mutator", "LLMResponse"),
    "LLMClient": (".llm_mutator", "LLMClient"),
    "MockLLMClient": (".llm_mutator", "MockLLMClient"),
    "GroqClient": (".llm_mutator", "GroqClient"),
    "LLMCostTracker": (".llm_mutator", "LLMCostTracker"),
    "LLMSemanticMutator": (".llm_mutator", "LLMSemanticMutator"),
    "extract_python_code": (".llm_mutator", "extract_python_code"),
    "extract_json_payload": (".llm_mutator", "extract_json_payload"),
    "build_mutation_prompt": (".llm_mutator", "build_mutation_prompt"),
    "Opcode": (".asm_vm", "Opcode"),
    "Instruction": (".asm_vm", "Instruction"),
    "VirtualMachine": (".asm_vm", "VirtualMachine"),
    "VMExecutionResult": (".asm_vm", "VMExecutionResult"),
    "REGISTERS": (".asm_vm", "REGISTERS"),
    "OPCODE_CYCLES": (".asm_vm", "OPCODE_CYCLES"),
    "AssemblyGenome": (".assembly_genome", "AssemblyGenome"),
    "asm_distance": (".assembly_genome", "asm_distance"),
    "create_random_assembly_genome": (".assembly_genome", "create_random_assembly_genome"),
    "AssemblyHardwareEvaluator": (".asm_evaluators", "AssemblyHardwareEvaluator"),
    "AssemblyScenario": (".asm_benchmarks", "AssemblyScenario"),
    "ASM_SCENARIOS": (".asm_benchmarks", "ASM_SCENARIOS"),
    "get_all_asm_scenarios": (".asm_benchmarks", "get_all_asm_scenarios"),
    "scenario_branchless_min": (".asm_benchmarks", "scenario_branchless_min"),
    "scenario_branchless_abs": (".asm_benchmarks", "scenario_branchless_abs"),
    "scenario_fast_popcount": (".asm_benchmarks", "scenario_fast_popcount"),
    "scenario_euclidean_gcd": (".asm_benchmarks", "scenario_euclidean_gcd"),
    "scenario_fibonacci_n": (".asm_benchmarks", "scenario_fibonacci_n"),
    "pauli_x": (".quantum", "pauli_x"),
    "pauli_y": (".quantum", "pauli_y"),
    "pauli_z": (".quantum", "pauli_z"),
    "hadamard": (".quantum", "hadamard"),
    "cnot": (".quantum", "cnot"),
    "cz": (".quantum", "cz"),
    "swap_gate": (".quantum", "swap_gate"),
    "average_gate_fidelity": (".quantum", "average_gate_fidelity"),
    "phase_invariant_fidelity": (".quantum", "phase_invariant_fidelity"),
    "QuantumPulseEvaluator": (".quantum", "QuantumPulseEvaluator"),
    "simulate_multi_axis_single_qubit": (".quantum", "simulate_multi_axis_single_qubit"),
    "simulate_two_qubit_entangling_evolution": (".quantum", "simulate_two_qubit_entangling_evolution"),
    "GateType": (".cgp_logic", "GateType"),
    "GATE_TRANSISTORS": (".cgp_logic", "GATE_TRANSISTORS"),
    "GATE_DELAYS": (".cgp_logic", "GATE_DELAYS"),
    "CGPNode": (".cgp_logic", "CGPNode"),
    "CircuitMetrics": (".cgp_logic", "CircuitMetrics"),
    "CGPGenome": (".cgp_logic", "CGPGenome"),
    "create_random_cgp_genome": (".cgp_logic", "create_random_cgp_genome"),
    "mutate_cgp_genome": (".cgp_logic", "mutate_cgp_genome"),
    "ALUEvaluator": (".cgp_logic", "ALUEvaluator"),
    "HALF_ADDER_TRUTH_TABLE": (".cgp_logic", "HALF_ADDER_TRUTH_TABLE"),
    "FULL_ADDER_TRUTH_TABLE": (".cgp_logic", "FULL_ADDER_TRUTH_TABLE"),
    "COMPARATOR_TRUTH_TABLE": (".cgp_logic", "COMPARATOR_TRUTH_TABLE"),
    "HierarchicalALUMetrics": (".cgp_logic", "HierarchicalALUMetrics"),
    "HierarchicalAdder8Bit": (".cgp_logic", "HierarchicalAdder8Bit"),
    "SwitchingMetrics": (".cgp_logic", "SwitchingMetrics"),
    "LowPowerALUEvaluator": (".cgp_logic", "LowPowerALUEvaluator"),
    "EDABundleReport": (".cgp_logic", "EDABundleReport"),
    "EDAPackager": (".cgp_logic", "EDAPackager"),
    "FaultCategory": (".instrumentation", "FaultCategory"),
    "classify_fault": (".instrumentation", "classify_fault"),
    "Target": (".instrumentation", "Target"),
    "Observation": (".instrumentation", "Observation"),
    "Invariant": (".instrumentation", "Invariant"),
    "Violation": (".instrumentation", "Violation"),
    "ViolationSeverity": (".instrumentation", "ViolationSeverity"),
    "ExpectedBehaviorInvariant": (".instrumentation", "ExpectedBehaviorInvariant"),
    "NoPrivilegeBoundaryViolationInvariant": (".instrumentation", "NoPrivilegeBoundaryViolationInvariant"),
    "NoMemorySafetyViolationInvariant": (".instrumentation", "NoMemorySafetyViolationInvariant"),
    "NoStateCorruptionInvariant": (".instrumentation", "NoStateCorruptionInvariant"),
    "NoResourceExhaustionInvariant": (".instrumentation", "NoResourceExhaustionInvariant"),
    "BoundedExecutionTimeInvariant": (".instrumentation", "BoundedExecutionTimeInvariant"),
    "SecurityOracle": (".instrumentation", "SecurityOracle"),
    "OracleVerdict": (".instrumentation", "OracleVerdict"),
    "DifferentialExecutor": (".instrumentation", "DifferentialExecutor"),
    "BehavioralDelta": (".instrumentation", "BehavioralDelta"),
    "SecurityEvaluator": (".instrumentation", "SecurityEvaluator"),
    "DifferentialEvaluator": (".instrumentation", "DifferentialEvaluator"),
    "MemoryArena": (".instrumentation", "MemoryArena"),
    "CrossTargetTransferMemory": (".instrumentation", "CrossTargetTransferMemory"),
    "TransferablePrimitive": (".instrumentation", "TransferablePrimitive"),
    "InvariantBehavioralDescriptor": (".instrumentation", "InvariantBehavioralDescriptor"),
    "PermutationSymmetricInputSummary": (".instrumentation", "PermutationSymmetricInputSummary"),
    "BehavioralSecurityDescriptor": (".instrumentation", "BehavioralSecurityDescriptor"),
    "TransferableBehavioralMotif": (".instrumentation", "TransferableBehavioralMotif"),
    "SearchStrategy": (".strategies", "SearchStrategy"),
    "GeneticAlgorithmStrategy": (".strategies", "GeneticAlgorithmStrategy"),
    "GreedySearchStrategy": (".strategies", "GreedySearchStrategy"),
    "get_search_strategy": (".strategies", "get_search_strategy"),
}


def __getattr__(name: str) -> Any:
    spec = _LAZY.get(name)
    if spec is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr = spec
    from importlib import import_module

    try:
        value = getattr(import_module(module_name, __name__), attr)
    except ImportError as exc:
        raise AttributeError(
            f"{name} requires optional dependency ({module_name}: {exc})"
        ) from exc
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(__all__) | set(globals()) | set(_LAZY))


__all__ = [
    "__version__",
    "RepairGenome",
    "RepairEdit",
    "catalog_edits",
    "apply_edits",
    "register_repair_pattern",
    "unregister_repair_pattern",
    "list_repair_patterns",
    "make_code_population",
    "EngineConfig",
    "SpeciationConfig",
    "QualityDiversityConfig",
    "MemoryConfig",
    "CSTGenome", "CSTConstantMutator", "CSTComparisonMutator", "CSTBinaryOpMutator", "CSTSemanticNodeCollector",
    "EliteTypeCheckGate", "TypeCheckResult",
    "GateType", "GATE_TRANSISTORS", "GATE_DELAYS", "CGPNode", "CircuitMetrics", "CGPGenome",
    "create_random_cgp_genome", "mutate_cgp_genome", "ALUEvaluator",
    "HALF_ADDER_TRUTH_TABLE", "FULL_ADDER_TRUTH_TABLE", "COMPARATOR_TRUTH_TABLE",
    "HierarchicalALUMetrics", "HierarchicalAdder8Bit", "SwitchingMetrics", "LowPowerALUEvaluator",
    "EDABundleReport", "EDAPackager",
    "EventBus", "EvolutionEvent", "GenerationEvaluatedEvent", "IndividualEvaluatedEvent", "MutationRejectedEvent", "RunCompletedEvent",
    "RunReport", "Issue", "parse_report", "save_report", "summarize",
    "EvolutionEngine", "Individual", "EvolabGenome", "FloatGenome",
    "Opcode", "Instruction", "VirtualMachine", "VMExecutionResult", "REGISTERS", "OPCODE_CYCLES",
    "AssemblyGenome", "asm_distance", "create_random_assembly_genome", "AssemblyHardwareEvaluator",
    "AssemblyScenario", "ASM_SCENARIOS", "get_all_asm_scenarios",
    "scenario_branchless_min", "scenario_branchless_abs", "scenario_fast_popcount",
    "scenario_euclidean_gcd", "scenario_fibonacci_n",
    "Hunk", "PatchGenome", "PatchApplyError", "apply_patch",
    "create_patch_from_diff", "patch_distance", "mutate_patch", "mutate_multi_hunk",
    "ASTGenome", "MultiFileASTGenome", "ast_distance", "mutate_ast", "crossover_ast",
    "get_ast_metrics", "compute_cyclomatic_complexity", "create_random_ast_genome",
    "CallSite", "ImportInfo", "CrossFileDependencyGraph", "CrossFileMutator",
    "Evaluator", "FitnessResult", "NumericEvaluator",
    "CompileCheckEvaluator", "FunctionTestEvaluator", "SandboxFunctionTestEvaluator",
    "SandboxConfig", "SandboxRunner", "ExecutionResult",
    "CodeScenario", "SCENARIO_REGISTRY", "get_all_scenarios",
    "load_scenario_file", "load_source_scenario",
    "scenario_click_parser", "scenario_requests_auth_url",
    "scenario_lru_cache_logic", "scenario_multi_file_config",
    "LLMConfig", "LLMResponse", "LLMClient", "MockLLMClient", "GroqClient",
    "LLMCostTracker", "LLMSemanticMutator", "extract_python_code",
    "default_fitness", "genomic_distance", "ragged_fitness", "species_cfg", "SPECIES_POOL",
    "FitnessLandscape", "SmoothProxyLandscape", "RastriginLandscape",
    "TrapKLandscape", "NoisyWrapper", "MovingTargetLandscape",
    "CausalEvent", "CausalModel", "TrapSignatureLibrary",
    "StrategicMutationSelector", "discretize_context", "discretize_code_context",
    "ExperienceStore", "ExperienceMutationPrior", "ExperienceSequencePrior",
    "EvaluationCache", "attach_eval_cache",
    "function_summaries", "render_family_report",
    "pauli_x", "pauli_y", "pauli_z", "hadamard", "cnot", "cz", "swap_gate",
    "average_gate_fidelity", "phase_invariant_fidelity", "QuantumPulseEvaluator",
    "ZProtocolConfig", "ZProtocolEngine",
    "FaultCategory", "classify_fault",
    "Target", "Observation", "Invariant", "Violation", "ViolationSeverity",
    "ExpectedBehaviorInvariant", "NoPrivilegeBoundaryViolationInvariant",
    "NoMemorySafetyViolationInvariant",
    "NoStateCorruptionInvariant", "NoResourceExhaustionInvariant",
    "BoundedExecutionTimeInvariant",
    "SecurityOracle", "OracleVerdict",
    "DifferentialExecutor", "BehavioralDelta",
    "SecurityEvaluator", "DifferentialEvaluator",
    "MemoryArena", "CrossTargetTransferMemory", "TransferablePrimitive",
    "NodeType", "NodeMetadata", "CriticalityLevel", "Symbol", "TypeInfo", "SymbolTable",
    "DeepAnalyzer", "DependencyAnalyzer", "IntelligentMutator", "BalancedMutator",
    "IntelligentCrossover", "ASTOptimizer", "RealASTGenome",
    "ASTSemanticGuard", "is_ast_change_safe",
    "SuspicionMap", "SuspiciousNode", "LineCoverageTracer", "build_suspicion_map",
    "NodeAnchor", "AnchoredHunk", "AnchoredPatchGenome", "apply_anchored_hunk", "AnchoredPatchApplyError",
    "SearchStrategy", "GeneticAlgorithmStrategy", "GreedySearchStrategy", "get_search_strategy",
    "DomainAdapter", "SoftwareRepairAdapter", "DiscreteLogicAdapter", "NumericalMathAdapter", "ElectronicsAdapter",
    "register_domain_adapter", "get_domain_adapter", "list_domain_adapters",
    "NSGA2Engine", "fast_non_dominated_sort", "calculate_crowding_distance", "Objective", "MultiObjectiveResult",
    "build_silicon_multiobjective_evaluator", "SWEBenchAdapter", "SWEBenchInstance", "SWEBenchResolution",
]
