"""evolab — Universal Evolutionary Optimization & Synthesis Kernel across Software, Silicon, Discrete Logic, and Mathematics.

Importing this package loads the core evolutionary kernel and domain adapter contracts.
"""
from __future__ import annotations

from typing import Any

__version__ = "0.5.0"

from .adapters import (
    DomainAdapter,
    DiscreteLogicAdapter,
    NumericalMathAdapter,
    SoftwareRepairAdapter,
    get_domain_adapter,
    list_domain_adapters,
    register_domain_adapter,
)
from .pareto import (
    NSGA2Engine,
    Objective,
    MultiObjectiveResult,
    fast_non_dominated_sort,
    calculate_crowding_distance,
    build_silicon_multiobjective_evaluator,
)
from .swe_bench import (
    SWEBenchAdapter,
    SWEBenchInstance,
    SWEBenchResolution,
)
from .vectorized import VectorizedLandscapeEvaluator
from .analyzer import summarize
from .code_fixtures import (
    SCENARIO_REGISTRY,
    CodeScenario,
    get_all_scenarios,
    load_pytest_scenario,
    load_scenario_file,
    load_source_scenario,
    make_code_population,
    scenario_click_parser,
    scenario_lru_cache_logic,
    scenario_multi_file_config,
    scenario_requests_auth_url,
)
from .config import EngineConfig, MemoryConfig, QualityDiversityConfig, SpeciationConfig
from .engine import (
    SPECIES_POOL,
    EvolutionEngine,
    default_fitness,
    genomic_distance,
    ragged_fitness,
    species_cfg,
)
from .evaluators import (
    CompileCheckEvaluator,
    Evaluator,
    FitnessResult,
    FunctionTestEvaluator,
    NumericEvaluator,
    SandboxFunctionTestEvaluator,
)
from .ipc_evaluator import ExternalProcessEvaluator
from .genome import EvolabGenome, FloatGenome, Individual
from .eval_cache import EvaluationCache, attach_eval_cache
from .repair import (
    RepairEdit,
    RepairGenome,
    apply_edits,
    catalog_edits,
    catalog_sources,
    greedy_repair,
    list_repair_patterns,
    parsimony_prune,
    register_repair_pattern,
    unified_source_diff,
    unregister_repair_pattern,
)
from .reporters import (
    apply_in_place,
    format_git_patch,
    format_markdown_summary,
    format_terminal_diagnostics,
)
from .schema import Issue, RunReport, parse_report, save_report

_LAZY: dict[str, tuple[str, str]] = {
    # patch / AST / CST
    "Hunk": (".patch", "Hunk"),
    "PatchGenome": (".patch", "PatchGenome"),
    "PatchApplyError": (".patch", "PatchApplyError"),
    "apply_patch": (".patch", "apply_patch"),
    "create_patch_from_diff": (".patch", "create_patch_from_diff"),
    "patch_distance": (".patch", "patch_distance"),
    "mutate_patch": (".patch", "mutate_patch"),
    "mutate_multi_hunk": (".patch", "mutate_multi_hunk"),
    "NodeAnchor": (".anchored_patch", "NodeAnchor"),
    "AnchoredHunk": (".anchored_patch", "AnchoredHunk"),
    "AnchoredPatchGenome": (".anchored_patch", "AnchoredPatchGenome"),
    "apply_anchored_hunk": (".anchored_patch", "apply_anchored_hunk"),
    "AnchoredPatchApplyError": (".anchored_patch", "AnchoredPatchApplyError"),
    "ASTSemanticGuard": (".ast_guard", "ASTSemanticGuard"),
    "is_ast_change_safe": (".ast_guard", "is_ast_change_safe"),
    "ASTGenome": (".ast_genome", "ASTGenome"),
    "MultiFileASTGenome": (".ast_genome", "MultiFileASTGenome"),
    "ast_distance": (".ast_genome", "ast_distance"),
    "mutate_ast": (".ast_genome", "mutate_ast"),
    "crossover_ast": (".ast_genome", "crossover_ast"),
    "get_ast_metrics": (".ast_genome", "get_ast_metrics"),
    "compute_cyclomatic_complexity": (".ast_genome", "compute_cyclomatic_complexity"),
    "create_random_ast_genome": (".ast_genome", "create_random_ast_genome"),
    "CSTGenome": (".cst_genome", "CSTGenome"),
    "CSTConstantMutator": (".cst_genome", "CSTConstantMutator"),
    "CSTComparisonMutator": (".cst_genome", "CSTComparisonMutator"),
    "CSTBinaryOpMutator": (".cst_genome", "CSTBinaryOpMutator"),
    "CSTSemanticNodeCollector": (".cst_genome", "CSTSemanticNodeCollector"),
    "NodeType": (".real_ast", "NodeType"),
    "NodeMetadata": (".real_ast", "NodeMetadata"),
    "CriticalityLevel": (".real_ast", "CriticalityLevel"),
    "Symbol": (".real_ast", "Symbol"),
    "TypeInfo": (".real_ast", "TypeInfo"),
    "SymbolTable": (".real_ast", "SymbolTable"),
    "DeepAnalyzer": (".real_ast", "DeepAnalyzer"),
    "DependencyAnalyzer": (".real_ast", "DependencyAnalyzer"),
    "IntelligentMutator": (".real_ast", "IntelligentMutator"),
    "BalancedMutator": (".real_ast", "BalancedMutator"),
    "IntelligentCrossover": (".real_ast", "IntelligentCrossover"),
    "ASTOptimizer": (".real_ast", "ASTOptimizer"),
    "RealASTGenome": (".real_ast", "RealASTGenome"),
    "SuspicionMap": (".suspicion", "SuspicionMap"),
    "SuspiciousNode": (".suspicion", "SuspiciousNode"),
    "LineCoverageTracer": (".suspicion", "LineCoverageTracer"),
    "build_suspicion_map": (".suspicion", "build_suspicion_map"),
    "FaultGuidedASTMutator": (".suspicion", "FaultGuidedASTMutator"),
    "compute_ochiai_score": (".suspicion", "compute_ochiai_score"),
    "compositional_repair": (".compositional", "compositional_repair"),
    "SuspicionCluster": (".compositional", "SuspicionCluster"),
    "cluster_edits_by_proximity": (".compositional", "cluster_edits_by_proximity"),
    "generate_dual_hunk_candidates": (".compositional", "generate_dual_hunk_candidates"),
    "SandboxConfig": (".sandbox", "SandboxConfig"),
    "SandboxRunner": (".sandbox", "SandboxRunner"),
    "ExecutionResult": (".sandbox", "ExecutionResult"),
    "EliteTypeCheckGate": (".type_gate", "EliteTypeCheckGate"),
    "TypeCheckResult": (".type_gate", "TypeCheckResult"),
    "CallSite": (".cross_file", "CallSite"),
    "ImportInfo": (".cross_file", "ImportInfo"),
    "CrossFileDependencyGraph": (".cross_file", "CrossFileDependencyGraph"),
    "CrossFileMutator": (".cross_file", "CrossFileMutator"),
    "EventBus": (".events", "EventBus"),
    "EvolutionEvent": (".events", "EvolutionEvent"),
    "GenerationEvaluatedEvent": (".events", "GenerationEvaluatedEvent"),
    "IndividualEvaluatedEvent": (".events", "IndividualEvaluatedEvent"),
    "MutationRejectedEvent": (".events", "MutationRejectedEvent"),
    "RunCompletedEvent": (".events", "RunCompletedEvent"),
    "EvaluationTimeoutEvent": (".events", "EvaluationTimeoutEvent"),
    "WorkerRecycledEvent": (".events", "WorkerRecycledEvent"),
    "ParallelBudgetExecutor": (".parallel_budget_executor", "ParallelBudgetExecutor"),
    "BudgetConfig": (".parallel_budget_executor", "BudgetConfig"),
    "BudgetResult": (".parallel_budget_executor", "BudgetResult"),
    "EvolutionSignal": (".signals", "EvolutionSignal"),
    "SignalController": (".signals", "SignalController"),
    "CheckpointData": (".checkpoint", "CheckpointData"),
    "save_checkpoint": (".checkpoint", "save_checkpoint"),
    "load_checkpoint": (".checkpoint", "load_checkpoint"),
    "JournalRecord": (".journal", "JournalRecord"),
    "StructuredJournal": (".journal", "StructuredJournal"),
    "load_hierarchical_config": (".config", "load_hierarchical_config"),
    "get_config_provenance": (".config", "get_config_provenance"),
    "FitnessLandscape": (".landscapes", "FitnessLandscape"),
    "SmoothProxyLandscape": (".landscapes", "SmoothProxyLandscape"),
    "RastriginLandscape": (".landscapes", "RastriginLandscape"),
    "TrapKLandscape": (".landscapes", "TrapKLandscape"),
    "NoisyWrapper": (".landscapes", "NoisyWrapper"),
    "MovingTargetLandscape": (".landscapes", "MovingTargetLandscape"),
    "build_landscape": (".landscapes", "build_landscape"),
    "CausalEvent": (".causal", "CausalEvent"),
    "CausalModel": (".causal", "CausalModel"),
    "TrapSignatureLibrary": (".causal", "TrapSignatureLibrary"),
    "StrategicMutationSelector": (".causal", "StrategicMutationSelector"),
    "discretize_context": (".causal", "discretize_context"),
    "discretize_code_context": (".causal", "discretize_code_context"),
    "ExperienceStore": (".experience", "ExperienceStore"),
    "ExperienceMutationPrior": (".priors", "ExperienceMutationPrior"),
    "ExperienceSequencePrior": (".priors", "ExperienceSequencePrior"),
    "ExperienceRecorderProxy": (".experience", "ExperienceRecorderProxy"),
    "attach_experience_recorder": (".experience", "attach_experience_recorder"),
    "SelfEvolutionEngine": (".self_evolution", "SelfEvolutionEngine"),
    "MetaProposal": (".self_evolution", "MetaProposal"),
    "EvaluationCache": (".eval_cache", "EvaluationCache"),
    "attach_eval_cache": (".eval_cache", "attach_eval_cache"),
    "problem_fingerprint": (".experience", "problem_fingerprint"),
    "function_summaries": (".experience", "function_summaries"),
    "render_family_report": (".experience", "render_family_report"),
    "ZProtocolConfig": (".z_protocol", "ZProtocolConfig"),
    "ZProtocolEngine": (".z_protocol", "ZProtocolEngine"),
    "LLMConfig": (".llm_mutator", "LLMConfig"),
    "LLMResponse": (".llm_mutator", "LLMResponse"),
    "LLMClient": (".llm_mutator", "LLMClient"),
    "MockLLMClient": (".llm_mutator", "MockLLMClient"),
    "GroqClient": (".llm_mutator", "GroqClient"),
    "LLMCostTracker": (".llm_mutator", "LLMCostTracker"),
    "LLMSemanticMutator": (".llm_mutator", "LLMSemanticMutator"),
    "extract_python_code": (".llm_mutator", "extract_python_code"),
    "extract_json_payload": (".llm_mutator", "extract_json_payload"),
    "build_mutation_prompt": (".llm_mutator", "build_mutation_prompt"),
    "Opcode": (".asm_vm", "Opcode"),
    "Instruction": (".asm_vm", "Instruction"),
    "VirtualMachine": (".asm_vm", "VirtualMachine"),
    "VMExecutionResult": (".asm_vm", "VMExecutionResult"),
    "REGISTERS": (".asm_vm", "REGISTERS"),
    "OPCODE_CYCLES": (".asm_vm", "OPCODE_CYCLES"),
    "AssemblyGenome": (".assembly_genome", "AssemblyGenome"),
    "asm_distance": (".assembly_genome", "asm_distance"),
    "create_random_assembly_genome": (".assembly_genome", "create_random_assembly_genome"),
    "AssemblyHardwareEvaluator": (".asm_evaluators", "AssemblyHardwareEvaluator"),
    "AssemblyScenario": (".asm_benchmarks", "AssemblyScenario"),
    "ASM_SCENARIOS": (".asm_benchmarks", "ASM_SCENARIOS"),
    "get_all_asm_scenarios": (".asm_benchmarks", "get_all_asm_scenarios"),
    "scenario_branchless_min": (".asm_benchmarks", "scenario_branchless_min"),
    "scenario_branchless_abs": (".asm_benchmarks", "scenario_branchless_abs"),
    "scenario_fast_popcount": (".asm_benchmarks", "scenario_fast_popcount"),
    "scenario_euclidean_gcd": (".asm_benchmarks", "scenario_euclidean_gcd"),
    "scenario_fibonacci_n": (".asm_benchmarks", "scenario_fibonacci_n"),
    "pauli_x": (".quantum", "pauli_x"),
    "pauli_y": (".quantum", "pauli_y"),
    "pauli_z": (".quantum", "pauli_z"),
    "hadamard": (".quantum", "hadamard"),
    "cnot": (".quantum", "cnot"),
    "cz": (".quantum", "cz"),
    "swap_gate": (".quantum", "swap_gate"),
    "average_gate_fidelity": (".quantum", "average_gate_fidelity"),
    "phase_invariant_fidelity": (".quantum", "phase_invariant_fidelity"),
    "QuantumPulseEvaluator": (".quantum", "QuantumPulseEvaluator"),
    "simulate_multi_axis_single_qubit": (".quantum", "simulate_multi_axis_single_qubit"),
    "simulate_two_qubit_entangling_evolution": (".quantum", "simulate_two_qubit_entangling_evolution"),
    "GateType": (".cgp_logic", "GateType"),
    "GATE_TRANSISTORS": (".cgp_logic", "GATE_TRANSISTORS"),
    "GATE_DELAYS": (".cgp_logic", "GATE_DELAYS"),
    "CGPNode": (".cgp_logic", "CGPNode"),
    "CircuitMetrics": (".cgp_logic", "CircuitMetrics"),
    "CGPGenome": (".cgp_logic", "CGPGenome"),
    "create_random_cgp_genome": (".cgp_logic", "create_random_cgp_genome"),
    "mutate_cgp_genome": (".cgp_logic", "mutate_cgp_genome"),
    "measure_neutrality": (".cgp_logic", "measure_neutrality"),
    "classify_mutation": (".cgp_logic", "classify_mutation"),
    "evolve_cgp": (".cgp_logic", "evolve_cgp"),
    "ALUEvaluator": (".cgp_logic", "ALUEvaluator"),
    "HALF_ADDER_TRUTH_TABLE": (".cgp_logic", "HALF_ADDER_TRUTH_TABLE"),
    "FULL_ADDER_TRUTH_TABLE": (".cgp_logic", "FULL_ADDER_TRUTH_TABLE"),
    "COMPARATOR_TRUTH_TABLE": (".cgp_logic", "COMPARATOR_TRUTH_TABLE"),
    "HierarchicalALUMetrics": (".cgp_logic", "HierarchicalALUMetrics"),
    "HierarchicalAdder8Bit": (".cgp_logic", "HierarchicalAdder8Bit"),
    "SwitchingMetrics": (".cgp_logic", "SwitchingMetrics"),
    "LowPowerALUEvaluator": (".cgp_logic", "LowPowerALUEvaluator"),
    "EDABundleReport": (".cgp_logic", "EDABundleReport"),
    "EDAPackager": (".cgp_logic", "EDAPackager"),
    "FPGABoardSpec": (".cgp_logic", "FPGABoardSpec"),
    "FPGA_PRESETS": (".cgp_logic", "FPGA_PRESETS"),
    "FPGAResourceReport": (".cgp_logic", "FPGAResourceReport"),
    "estimate_fpga_resources": (".cgp_logic", "estimate_fpga_resources"),
    "FaultCategory": (".instrumentation", "FaultCategory"),
    "classify_fault": (".instrumentation", "classify_fault"),
    "Target": (".instrumentation", "Target"),
    "Observation": (".instrumentation", "Observation"),
    "Invariant": (".instrumentation", "Invariant"),
    "Violation": (".instrumentation", "Violation"),
    "ViolationSeverity": (".instrumentation", "ViolationSeverity"),
    "ExpectedBehaviorInvariant": (".instrumentation", "ExpectedBehaviorInvariant"),
    "NoPrivilegeBoundaryViolationInvariant": (".instrumentation", "NoPrivilegeBoundaryViolationInvariant"),
    "NoMemorySafetyViolationInvariant": (".instrumentation", "NoMemorySafetyViolationInvariant"),
    "NoStateCorruptionInvariant": (".instrumentation", "NoStateCorruptionInvariant"),
    "NoResourceExhaustionInvariant": (".instrumentation", "NoResourceExhaustionInvariant"),
    "BoundedExecutionTimeInvariant": (".instrumentation", "BoundedExecutionTimeInvariant"),
    "SecurityOracle": (".instrumentation", "SecurityOracle"),
    "OracleVerdict": (".instrumentation", "OracleVerdict"),
    "DifferentialExecutor": (".instrumentation", "DifferentialExecutor"),
    "BehavioralDelta": (".instrumentation", "BehavioralDelta"),
    "SecurityEvaluator": (".instrumentation", "SecurityEvaluator"),
    "DifferentialEvaluator": (".instrumentation", "DifferentialEvaluator"),
    "MemoryArena": (".instrumentation", "MemoryArena"),
    "CrossTargetTransferMemory": (".instrumentation", "CrossTargetTransferMemory"),
    "TransferablePrimitive": (".instrumentation", "TransferablePrimitive"),
    "InvariantBehavioralDescriptor": (".instrumentation", "InvariantBehavioralDescriptor"),
    "PermutationSymmetricInputSummary": (".instrumentation", "PermutationSymmetricInputSummary"),
    "BehavioralSecurityDescriptor": (".instrumentation", "BehavioralSecurityDescriptor"),
    "TransferableBehavioralMotif": (".instrumentation", "TransferableBehavioralMotif"),
    "SearchStrategy": (".strategies", "SearchStrategy"),
    "GeneticAlgorithmStrategy": (".strategies", "GeneticAlgorithmStrategy"),
    "GreedySearchStrategy": (".strategies", "GreedySearchStrategy"),
    "get_search_strategy": (".strategies", "get_search_strategy"),
    "HollandTrialAllocator": (".holland", "HollandTrialAllocator"),
    "Schema": (".holland", "Schema"),
    "SchemaTracker": (".holland", "SchemaTracker"),
    "Sky130Corner": (".silicon", "Sky130Corner"),
    "SKY130_PARAMS": (".silicon", "SKY130_PARAMS"),
    "compute_transistor_operating_point": (".silicon", "compute_transistor_operating_point"),
    "generate_sky130_spice_header": (".silicon", "generate_sky130_spice_header"),
    "OpAmpSizing": (".silicon", "OpAmpSizing"),
    "OpAmpPerformanceMetrics": (".silicon", "OpAmpPerformanceMetrics"),
    "evaluate_opamp_analytical": (".silicon", "evaluate_opamp_analytical"),
    "generate_opamp_spice_netlist": (".silicon", "generate_opamp_spice_netlist"),
    "TwoStageMillerOpAmpEvaluator": (".silicon", "TwoStageMillerOpAmpEvaluator"),
    "Sky130OpAmpAdapter": (".silicon", "Sky130OpAmpAdapter"),
    "SpiceNeuralSurrogate": (".silicon", "SpiceNeuralSurrogate"),
    "ActiveSpiceSurrogateEvaluator": (".silicon", "ActiveSpiceSurrogateEvaluator"),
    "YosysCellReport": (".silicon", "YosysCellReport"),
    "YosysComparisonReport": (".silicon", "YosysComparisonReport"),
    "YosysSynthesisBridge": (".silicon", "YosysSynthesisBridge"),
    # Replay Simulator & Discovery Trees (Dream-RSI)
    "DiscoveryNode": (".replay_simulator", "DiscoveryNode"),
    "DiscoveryTree": (".replay_simulator", "DiscoveryTree"),
    "ReplaySimulator": (".replay_simulator", "ReplaySimulator"),
    "ReplayObjective": (".replay_simulator", "ReplayObjective"),
    "ExplorationPolicy": (".replay_simulator", "ExplorationPolicy"),
    "GreedyBestFirstPolicy": (".replay_simulator", "GreedyBestFirstPolicy"),
    "BreadthFirstPolicy": (".replay_simulator", "BreadthFirstPolicy"),
    "AdaptivePlateauPolicy": (".replay_simulator", "AdaptivePlateauPolicy"),
    # Dream Subsystem: Autonomous Operator Reweighting & Governor Verification (Dream-RSI)
    "OperatorDistribution": (".dream", "OperatorDistribution"),
    "OperatorReweighter": (".dream", "OperatorReweighter"),
    "DreamReweightingResult": (".dream", "DreamReweightingResult"),
    "sample_dirichlet_weights": (".dream", "sample_dirichlet_weights"),
    "run_dream_reweighting": (".dream", "run_dream_reweighting"),
    # Dream Subsystem: Budget Elasticity & Stagnation Breaking (Idea 2)
    "ElasticityConfig": (".dream", "ElasticityConfig"),
    "BudgetElasticityPolicy": (".dream", "BudgetElasticityPolicy"),
    "BudgetElasticityOptimizer": (".dream", "BudgetElasticityOptimizer"),
    "DreamElasticityResult": (".dream", "DreamElasticityResult"),
    "run_budget_elasticity_dreaming": (".dream", "run_budget_elasticity_dreaming"),
    # Dream Subsystem: M8 & M9 Cross-Validated Seeding (Idea 3)
    "SeedCandidate": (".dream", "SeedCandidate"),
    "SeedingConfig": (".dream", "SeedingConfig"),
    "SeedingPolicy": (".dream", "SeedingPolicy"),
    "CrossValidatedSeedingResult": (".dream", "CrossValidatedSeedingResult"),
    "CrossValidatedSeedingOptimizer": (".dream", "CrossValidatedSeedingOptimizer"),
    "compute_seed_affinity": (".dream", "compute_seed_affinity"),
    "mine_seeds_from_trees": (".dream", "mine_seeds_from_trees"),
    "train_test_split_trees": (".dream", "train_test_split_trees"),
    "run_cross_validated_seeding": (".dream", "run_cross_validated_seeding"),
}


def __getattr__(name: str) -> Any:
    spec = _LAZY.get(name)
    if spec is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr = spec
    from importlib import import_module

    try:
        value = getattr(import_module(module_name, __name__), attr)
    except ImportError as exc:
        raise AttributeError(
            f"{name} requires optional dependency ({module_name}: {exc})"
        ) from exc
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(__all__) | set(globals()) | set(_LAZY))


# -----------------------------------------------------------------------------
# STABLE PUBLIC API CONTRACT
# Core interfaces and contracts documented in README.md & README_ar.md.
# Specialized domain adapters, hardware bridges, and experimental research
# modules remain accessible via lazy import or their dedicated subpackages:
#   - evolab.silicon
#   - evolab.quantum
#   - evolab.genesis
#   - evolab.vectorized
# -----------------------------------------------------------------------------
__all__ = [
    "__version__",
    # 1. Program Repair Core Contracts (README_ar.md: "API البرمجي — مسار الشيفرة")
    "CodeScenario",
    "SCENARIO_REGISTRY",
    "get_all_scenarios",
    "load_scenario_file",
    "load_source_scenario",
    "load_pytest_scenario",
    "make_code_population",
    "greedy_repair",
    "compositional_repair",
    "unified_source_diff",
    "RepairGenome",
    "RepairEdit",
    "catalog_edits",
    "catalog_sources",
    "apply_edits",
    "register_repair_pattern",
    "unregister_repair_pattern",
    "list_repair_patterns",
    # 2. Evaluator & Fitness Core Contracts
    "Evaluator",
    "FitnessResult",
    "FunctionTestEvaluator",
    "SandboxFunctionTestEvaluator",
    "CompileCheckEvaluator",
    "NumericEvaluator",
    "ExternalProcessEvaluator",
    "EvaluationCache",
    "attach_eval_cache",
    # 3. Evolution Engine Core Contracts (README_ar.md: "API البرمجي — مسار الأرقام")
    "EvolutionEngine",
    "EngineConfig",
    "SpeciationConfig",
    "QualityDiversityConfig",
    "MemoryConfig",
    "Individual",
    "EvolabGenome",
    "FloatGenome",
    "SearchStrategy",
    "get_search_strategy",
    "NSGA2Engine",
    # 4. Multi-Domain Architecture
    "DomainAdapter",
    "register_domain_adapter",
    "get_domain_adapter",
    "list_domain_adapters",
    "SoftwareRepairAdapter",
    "DiscreteLogicAdapter",
    "NumericalMathAdapter",
    # 5. Reporting & Summary
    "RunReport",
    "Issue",
    "parse_report",
    "save_report",
    "summarize",
    "EventBus",
    "EvolutionEvent",
]
